# Generated by Django 3.0.3 on 2020-06-09 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_amar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gmail', models.EmailField(max_length=254)),
                ('commen', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Article')),
            ],
        ),
    ]
